development:
  adapter: postgresql
  encoding: unicode
  database: pair_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pair_test
  pool: 5
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: pair_production
  pool: 5
  password:
  host: localhost
