- name: 'Mathew Wilson O’Day'
  email: 'mathew@withassociates.com'
  skills: 'Design, UX, Project Management, Running a Business'

- name: 'Erin Staniland'
  email: 'erin@withassociates.com'
  skills: 'Ruby, Systems Architecture, Running a Business'

- name: 'Jenifer Dunn'
  email: 'jenifer@withassociates.com'
  skills: 'Javascript, CSS, Running a Business'

- name: 'Anna Goss'
  email: 'anna@withassociates.com'
  skills: 'UX, Project Management'

- name: 'Jamie White'
  email: 'jamie@withassociates.com'
  skills: 'Ruby, Javascript, Ember.js, CSS'

- name: 'Thomas Marshall'
  email: 'thomas@withassociates.com'
  skills: 'Javascript, CSS, Ruby'

- name: 'Brendan Gatens'
  email: 'brendan@withassociates.com'
  skills: 'Design, UX, CSS'

- name: 'Joseph Morrow'
  email: 'joseph@withassociates.com'
  skills: 'Design, UX, CSS, Javascript'

- name: 'Calum Gunn'
  email: 'calum@withassociates.com'
  skills: 'Ruby, Rails, Javascript, CSS'
